[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "ema9-21-bot"
version = "0.1.0"
description = "EMA Trading Bot"
dependencies = [
    "ccxt==4.2.23",
    "pandas==2.0.3",
    "ta==0.10.2",
    "python-telegram-bot==20.3",
    "requests==2.31.0",
]
